name: "Get Container Image Tag"
description: "Get the latest tag for a container image"
author: "David van der Spek"
branding:
  icon: tag
  color: purple
inputs:
  org:
    description: The Docker Hub org
    required: true
  repo:
    description: The Docker Hub repo
    required: true
outputs:
  tag:
    description: The latest tag
runs:
  using: "docker"
  image: "Dockerfile"
