name: "Get Container Image Tag"
description: "Get the latest tag for a container image"
author: "David van der Spek"
branding:
  icon: tag
  color: purple
inputs:
  img:
    description: The container image
    required: true
outputs:
  latest_tag:
    description: The latest tag
  new_major:
    description: Next Major Version
  new_minor:
    description: Next Minor Version
  new_patch:
    description: Next Patch Version
  new_v_major:
    description: Next Major Version (prefixed with v)
  new_v_minor:
    description: Next Minor Version (prefixed with v)
  new_v_patch:
    description: Next Patch Version (prefixed with v)

runs:
  using: "docker"
  image: "Dockerfile"
