name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Self test
        id: selftest
        uses: jacobtomlinson/gha-get-docker-hub-tags@master
        with:
          org: mysql
          package: mysql-server

      - name: Check outputs
        run: |
          echo "${{ steps.selftest.outputs.version }}"
